import { Platform, StatusBar, StyleSheet } from 'react-native'

export default StyleSheet.create({
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingTop: Platform.OS === 'android'
      ? (StatusBar.currentHeight || 24) + 10
      : Platform.OS === 'web'
        ? 12
        : 50,
    paddingBottom: 15,
    paddingHorizontal: 15,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 10,
  },
  arrowBack: {
    padding: 10,
    marginLeft: 5,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  locationIndicator: {
    position: 'absolute',
    right: 20,
    top: Platform.OS === 'android'
      ? (StatusBar.currentHeight || 24) + 15
      : Platform.OS === 'web'
        ? 18
        : 55,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  locationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  searchbar: {
    flex: 1,
    marginHorizontal: 10,
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60%',
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 10,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  bottomSheetHandle: {
    height: 4,
    width: 40,
    backgroundColor: '#d9d9d9',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 0,
    marginBottom: 0,
  },
  bottomSheetBody: {
    flex: 1,
    minHeight: 0,
  },
  verticalListContainer: {
    flex: 1,
    minHeight: 0,
  },
  verticalList: {
    flex: 1,
  },
  flatlist: {
    position: 'absolute',
    bottom: Platform.OS === 'web' ? 64 : 0,
    left: 0,
    right: 0,
    paddingBottom: Platform.OS === 'web' ? 8 : 30,
    paddingLeft: 0,
    zIndex: 30,
    elevation: 30,
  },
  categories: {
    marginBottom: 4,
    marginTop: 0,
  },
  restaurant: {
    borderRadius: 15,
    backgroundColor: '#ffffff',
    marginHorizontal: 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  restaurantImageInfo: {
    marginHorizontal: 0,
    paddingHorizontal: 10,
    paddingBottom: 10,
    backgroundColor: '#ffffff',
  },
  menuList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 0,
    marginBottom: 0,
    minHeight: 0,
  },
  menuListBloc: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    width: 40,
    height: 40,
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    padding: 0,
    marginBottom: 0,
    marginTop: -4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    paddingBottom: Platform.OS === 'web' ? 4 : 20,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: '#111111',
    width: 12,
    height: 8,
    borderRadius: 4,
  },
})
